# Generated by Django 6.0.3 on 2026-03-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('review', 'Under Review'), ('interview', 'Interview'), ('rejected', 'Rejected'), ('selected', 'Selected')], default='applied', max_length=20),
        ),
    ]
