# Generated by Django 6.0.3 on 2026-03-09 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
