# Generated by Django 6.0.3 on 2026-03-10 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0005_jobopening_alter_application_job'),
        ('jobs', '0003_job_delete_jobopening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.job'),
        ),
        migrations.DeleteModel(
            name='JobOpening',
        ),
    ]
