# Generated by Django 6.0.3 on 2026-03-11 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0006_alter_application_job_delete_jobopening'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='experience',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
