# Generated by Django 6.0.3 on 2026-03-11 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0007_application_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ai_extracted_skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
