# Generated by Django 6.0.3 on 2026-03-12 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0008_application_ai_extracted_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateTimeField()),
                ('meet_link', models.URLField(blank=True, null=True)),
                ('application_name', models.CharField(max_length=255)),
                ('application_email', models.EmailField(max_length=254)),
                ('job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_interviews', to='careers.application')),
            ],
        ),
    ]
