# Generated by Django 6.0.3 on 2026-03-12 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0009_interview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interview',
        ),
    ]
