# Generated by Django 6.0.3 on 2026-03-12 14:16

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0010_delete_interview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(upload_to='resumes/', validators=[utils.validators.validate_file_extension, utils.validators.validate_file_size]),
        ),
    ]
