# Generated by Django 6.0.3 on 2026-03-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0005_jobopening_alter_application_job'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('image', models.CharField(help_text='Example: /software-develop.png', max_length=500)),
                ('overview', models.TextField()),
                ('description', models.TextField()),
                ('responsibilities', models.JSONField(default=list)),
                ('qualifications', models.JSONField(default=list)),
                ('technical', models.JSONField(default=list)),
                ('experience', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
