# Generated by Django 6.0.3 on 2026-03-10 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_job_description_alter_job_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(upload_to='jobs/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='overview',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='qualifications',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='job',
            name='responsibilities',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='job',
            name='technical',
            field=models.JSONField(default=list),
        ),
    ]
