# Generated by Django 6.0.3 on 2026-03-09 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_alter_application_status'),
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='careers.application'),
        ),
    ]
