# Generated by Django 6.0.3 on 2026-03-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmeeting',
            name='phone',
            field=models.CharField(default=6382141468, max_length=20),
            preserve_default=False,
        ),
    ]
