name: Deploy Django Backend
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/Deegenex-Backend
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            python3 manage.py migrate
            pm2 restart django-backend
            # Clean up old build traces and temp files
            sudo apt-get autoremove -y
            find . -type d -name "__pycache__" -exec rm -rf {} +
